---
title: "BFV-multiply"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BFV-multiply}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Load libraries that will be used.
```{r setup}
library(HomomorphicEncryption)
library(polynom)
```

Set some parameters.
```{r params}
d  =      4
n  =      2^d
p  =     (n/2)-1
q  = 424242
pm = GenPolyMod(n)
```

Set a working seed for random numbers
```{r}
set.seed(123)
```

Create the secret key and the polynomials a and e, which will go into the public key
```{r}
# generate a secret key
s = GenSecretKey(n)

# generate a
a = GenA(n, q)

# generate the error
e = GenError(n)
```

Generate the public key.
```{r}
# generate the public key
pk0 = GenPubKey0(a, s, e, pm, q)
pk1 = GenPubKey1(a)
```

Create polynomials for the encryption
```{r}
# polynomials for encryption
e1 = GenError(n)
e2 = GenError(n)
u  = GenU(n)
```

Now create to messages to add.
```{r}
m1 = polynomial(c(1, 1, 1))
m2 = polynomial(c(0, 1   ))
```

```{r}
m1_ct0 = EncryptPoly0(m1, pk0, u, e1, p, pm, q)
m1_ct1 = EncryptPoly1(    pk1, u, e2,    pm, q)
m2_ct0 = EncryptPoly0(m2, pk0, u, e1, p, pm, q)
m2_ct1 = EncryptPoly1(    pk1, u, e2,    pm, q)
```

Multiply the encrypted messages.
```{r}
multi_ct0 = m1_ct0 * m2_ct0 * (p/q)
multi_ct0 = multi_ct0 %% pm
multi_ct0 = CoefMod(multi_ct0, q)
multi_ct0 = round(multi_ct0)

multi_ct1 = (m1_ct0 * m2_ct1 + m1_ct1 * m2_ct0) * (p/q)
multi_ct1 = multi_ct1 %% pm
multi_ct1 = CoefMod(multi_ct1, q)
multi_ct1 = round(multi_ct1)

multi_ct2 = (m1_ct1 * m2_ct1) * (p/q)
multi_ct2 = multi_ct2 %% pm
multi_ct2 = CoefMod(multi_ct2, q)
multi_ct2 = round(multi_ct2)
```

Decrypt the sum
```{r}
decrypt = (multi_ct2 * s^2) + (multi_ct1 * s) + multi_ct0
decrypt = decrypt %% pm
decrypt = CoefMod(decrypt, q)

# rescale
decrypt = decrypt * p/q

# round then mod p
decrypt = CoefMod(round(decrypt), p)
print(decrypt)
```
